language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "scarspain"
    token:
      secure: "704cac83f93fafa1e5368f3bd44db83b6f8dc751"
script:
- ant build
- sonar-scanner
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=scarsPain_ProvaTravis
