language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "scarspain"
    token:
      secure: "travis encrypt 522515c360dbe566c3004cccc07245e71d7bbfc4"
script:
- ant build
- sonar-scanner
